import os
import re

log_dir = "/Users/duvanconde/.gemini/antigravity/brain/"
conversations = [
    "5836dc62-8679-45cd-a62a-7bfe0722ba5d",
    "526bf006-fa97-4ccb-9d64-59ca545d811d",
    "be073c2a-fb8b-4194-9587-bfaa9c3f06dd"
]

files_to_restore = [
    "product_detail_screen.dart",
    "rental_detail_screen.dart",
    "job_detail_screen.dart",
    "want_detail_screen.dart"
]

extracted = {}

for conv in reversed(conversations):
    log_path = os.path.join(log_dir, conv, ".system_generated/logs/overview.txt")
    if not os.path.exists(log_path):
        continue
    
    with open(log_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    for fname in files_to_restore:
        if fname in extracted:
            continue
        
        # Searching for the content output generated by view_file or in the user's initial state
        # The tool output looks like: 
        # File Path: `file:///.../product_detail_screen.dart`
        # Total Lines: X
        # Total Bytes: Y
        # Showing lines 1 to X
        # The following code has been modified to include a line number before every line...
        # 1: import '...'
        
        pattern = r"File Path: `file:///[^`]+/" + re.escape(fname) + r"`.*?\n1:\s(.*?\n)(?=\nThe above content|$)"
        match = re.search(pattern, content, re.DOTALL)
        if match:
            # We must strip the line numbers "1: ", "2: " etc.
            lines = ("1: " + match.group(1)).split('\n')
            clean_lines = []
            for line in lines:
                if not line.strip():
                    clean_lines.append(line)
                    continue
                # remove the prefix '\d+: '
                m = re.match(r'^\d+:\s(.*)', line)
                if m:
                    clean_lines.append(m.group(1))
            extracted[fname] = '\n'.join(clean_lines)

print(f"Extracted: {list(extracted.keys())}")

for fname, source in extracted.items():
    print(f"--- {fname} ({len(source)} bytes) ---")
    print(source[:200] + "...\n")
    
    # Let's save them to backups folder so we can easily restore them
    backup_path = f"/Users/duvanconde/Documents/proyectos/CONNECT/backups/{fname}"
    os.makedirs(os.path.dirname(backup_path), exist_ok=True)
    with open(backup_path, 'w', encoding='utf-8') as f:
        f.write(source)

